language: objective-c
osx_image: xcode9
rvm:
  - 2.2.2

env:
  global:
    - WORKSPACE="ArtifyWorkspace.xcworkspace"
    - OSX_APP_SCHEME="Artify"
    - FRAMEWORK_SCHEME="artify-core"
    - OSX_SDK=macosx10.12
  matrix:
    - DESTINATION="arch=x86_64"                      SCHEME="$OSX_APP_SCHEME"           SDK="$OSX_SDK"     RUN_TESTS="NO"    BUILD_EXAMPLE="YES"
    - DESTINATION="arch=x86_64"                      SCHEME="$FRAMEWORK_SCHEME"           SDK="$OSX_SDK"     RUN_TESTS="NO"    BUILD_EXAMPLE="NO"

before_install:
  - bundle install
  - bundle exec pod repo update
  - bundle exec pod install

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -list

    # Build Example in Debug if specified
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build | xcpretty;
    fi

    # Build Core in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -sdk "$SDK" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty;
    else
      xcodebuild -workspace "$WORKSPACE" -sdk "$SDK" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build | xcpretty;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
